[tox]
envlist =
    lint
    py{310,311}-dj32-cms311

skip_missing_interpreters=True

[testenv]
deps =
    -r{toxinidir}/tests/requirements/base.txt
    dj32: Django>=3.2,<4.0
    cms311: django-cms>=3.11,<4.0
commands =
    {envpython} --version
    coverage erase
    coverage run -m pytest
    coverage report

[testenv:lint]
skip_install = true
deps = ruff
commands =
    ruff check --fix .
