# Generated by Django 5.2.15 on 2026-06-11 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # The latest cms migration shared by django CMS 4.1 and 5.x
        ('cms', '0036_auto_20240311_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(max_length=255, verbose_name='Display name')),
                ('external_link', models.URLField(max_length=2040, verbose_name='External link')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
